# Generated by Django 3.2.2 on 2021-05-09 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='名前')),
                ('official_site', models.URLField(blank=True, null=True, verbose_name='公式サイト')),
                ('catalog_url', models.URLField(blank=True, null=True, verbose_name='カタログURL')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='cit_packs', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])], verbose_name='アイコン')),
            ],
            options={
                'verbose_name_plural': 'CITパック',
                'db_table': 'cit_packs',
            },
        ),
    ]
